### ISSUE TITLE
Form Completion

### ISSUE THREAD

**Issue by pralhad88** [navgurukul/kamla-bhasin#10]
### POST /users/details

- [x] using this endpoint user will able to insert their personal details.

- [x] Admin and super admin will be update, delete, the users details too

try to divide this task in step wise in a comment box.

**Comment by abhishekgupta92** [comment]
Pralhad, can you share the relevant code that we have already written in
Chanakya for this?

Abhishek Gupta <https://medium.com/@abhishekgupta92>
CEO & Co-founder
Read about us at Forbes India 30u30
<https://www.forbesindia.com/article/30-under-30-2020/navgurukul-cracking-the-code-to-success/57717/1>
, TOI
<https://timesofindia.indiatimes.com/home/sunday-times/these-school-dropouts-have-cracked-the-code-to-a-better-life/articleshow/71458732.cms>
or ZDNet
<http://www.zdnet.com/article/this-home-for-underprivileged-coders-will-put-the-indian-government-and-the-it-industry-to-shame/>
or
follow our blog <http://medium.com/navgurukul> for regular updates.
You can contribute now using navgurukul.org/donate. Each ruppee matters.

**Comment by pralhad88** [comment]
### below code is applicable to patch student personal details
`async patchStudentDetails(key, Details = {}, txn = null) {
    const details = Details;
    const { Student } = this.server.models();
    // update stage of student if specified
    if (details.stage) {
      await this.recordStageTranisiton(key.student, details.stage, txn);
    }

    if (details.whatsapp) {
      const { whatsapp } = details;
      await this.addOrUpdateWhatsappNumber(key.studentId, whatsapp, txn);
      delete details.whatsapp;
    }

    if (!details.name) { // patch the other details on the student table
      const patchStudentDetail = await Student.query(txn).patch(details)
        .where({ id: key.student.id });
      return patchStudentDetail;
    }
    const patchStudentDetail = await Student.query(txn).patch(details).where({ id: key.studentId });
    return patchStudentDetail;
  }`
### POST  /on_assessment/details/{enrolmentKey}
above end point took students relevant filed and then it patch into database. you can refer above API from chanakya.
