### ISSUE TITLE
Create CRUD for mentors 

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/kamla-bhasin#15]
There's a table called mentors already. Add a new column scope through migrations: 

It can only have either of the three values currently: english, tech, lifeskills

We can either

1. Insert a new relation
2. Update a new relation
3. Delete a new relation

**Comment by prakash-simhandri** [comment]
- [x] Create a migrations file for add column:

- [x] Write knex query for add column **scope** in mentors table.

- [x] Create a foreign key to connect from mentors to users tables 

- [x] And create a CRUD operation.
